'''
Script using .txt-output files generated by FLUKA MC simulations 
using the mgdraw_v05_detection.f script. 

Input/options: 
folder_directory: Where are the .txt-files stored?

This script uses the function collect_txt_data from 
mgdraw_v05_output_reader.py to collect data from a merged .txt file 
created by the function output_merger from mgdraw_output_merger_v2. 
'''

import time
import math
import matplotlib.pyplot as plt
#import matplotlib.animation as animation
#from mpl_toolkits.mplot3d.art3d import Poly3DCollection
#from mpl_toolkits.mplot3d import Axes3D
from mgdraw_v05_output_reader import collect_txt_data
from mgdraw_output_merger_v2 import output_merger

#------------------------------------------INPUT FOR USE------------------------------------------------
# ADD ONE FOLDER DIRECTORY

# Run with 200 MeV protons, 2M x 5 primaries, massive NOVCoDA model
folder_directory = r"C:\\Users\sathu8821\\OneDrive - University of Bergen\\NOVO\\FLUKA\\Delt mappe\\NOVCoDA_detection_07_08_25"

# ADD NUMBER OF PRIMARIES USED
primaries_per_spawn = 2000000

# ADD FLUKA RUN NAME
fluka_run_name = None

# ADD MGDRAW OUTPUT NAME
mgdraw_output_name = None

#------------------------------------------END OF INPUTS--------------------------------------------------
#---------------------------------DATA MERGING AND COLLECTION-------------------------------------------
# Merging all relevant files if merged file does not exist
merged_file_name = output_merger(
    folder_directory, fluka_run_name=fluka_run_name, 
    mgdraw_output_name=mgdraw_output_name
)

file_adress = folder_directory + r"\\" + merged_file_name

# Collecting data from the merged file
ncases, icodes, particles_in, particles_out, fnpg_flags, \
    targetZs, targetAs, energies_out, energies_in, \
    crash_xs, crash_ys, crash_zs, \
    regions, particles_generation, particles_age, \
    source_xs, source_ys, source_zs = \
    collect_txt_data(file_adress, primaries_per_spawn=primaries_per_spawn)


#-----------------------------EVENT BUILDING-------------------------------------

# Dictionary that will contain all compact gamma events {"Event1": [ICODE, JTRACK, ...]}
gamma_events = {}

# Dictionary that will contain all compact neutron events {"Event1": [ICODE, JTRACK, ...]}
neutron_events = {}

# Flag to indicate how many events are related to the "same" gamma/neutron
gamma_chain = 0
neutron_chain = 0

# Particle origin identification: The source coordinates
particle_id = [source_xs[0], source_ys[0], source_zs[0]]

# Variables to store previous gamma/neutron energies for chain logic checks
previous_gamma_energy = 0.0
previous_neutron_energy = 0.0

# Looping over all entries
for index, icode in enumerate(icodes):

    if particle_id != [source_xs[index], source_ys[index], source_zs[index]]:
        # If there is a new particle origin, then a new event chain is initiated
        gamma_chain = 0
        neutron_chain = 0
        particle_id = [source_xs[index], source_ys[index], source_zs[index]]

    # Compton interaction (219) will always have two list entries: on each for the outgoing photon and electron
    if icode == 219:
        if particles_out[index] == 3:
            # The compton electron is not interesting, so it is skipped
            continue

        elif particles_out[index] == 7:
            if gamma_chain == 0:
                gamma_chain += 1

            elif gamma_chain > 0:
                if previous_gamma_energy != energies_in[index]:
                    # The chain is irregular and might need supervision
                    # Chain is reset
                    gamma_chain = 1
                    print(f"Irregular gamma chain detected at {ncases[index]}" + \
                          f" Prev: {previous_gamma_energy} vs. now {energies_in[index]}")

                elif previous_gamma_energy == energies_in[index]:
                    gamma_chain += 1

            # Updating the previous_gamma_energy value
            previous_gamma_energy = energies_out[index]

            # Adding the Compton interaction to the gamma events
            gamma_events["Event" + str(len(gamma_events) + 1)] = \
                [crash_xs[index], crash_ys[index], crash_zs[index], \
                    source_xs[index], source_ys[index], source_zs[index], \
                    energies_out[index], energies_in[index], particles_age[index], \
                    particles_generation[index], targetAs[index], targetZs[index], \
                    icode, fnpg_flags[index], ncases[index]
                    ]
        else:
            assert 1==0, f"Non gamma/electron found in a Compton scatter: {particles_out[index]}" + \
                f" found in NCASE {ncases[index]}"
            
    #   221 events will alwyas have a single list entry
    elif icode == 221:
        # Photoelectric absorption events are generally the end
        gamma_chain += 1

        gamma_events["Event" + str(len(gamma_events) + 1)] = \
            [crash_xs[index], crash_ys[index], crash_zs[index], \
                source_xs[index], source_ys[index], source_zs[index], \
                energies_out[index], energies_in[index], particles_age[index], \
                particles_generation[index], targetAs[index], targetZs[index], \
                icode, fnpg_flags[index], ncases[index]
                ]

    elif icode == 100 and particles_in[index] == 8 and \
            targetAs[index] == 1 and targetZs[index] == 1:
        # Elastic 100 -interactions with (n, p) has two entries. The proton one is skipped
        if particles_out[index] == 1:
            # Skipping proton entry
            continue

        elif particles_out[index] == 8:
            if neutron_chain == 0:
                neutron_chain += 1

            elif neutron_chain > 0:
                if previous_neutron_energy != energies_in[index]:
                    # The neutron chain is irregular and might need supervision
                    # Chain is reset
                    neutron_chain = 1
                    print(f"Irregular neutron chain detected at {ncases[index]}")

                elif previous_neutron_energy == energies_in[index]:
                    neutron_chain += 1

            # Updating previous neutron energy values
            previous_neutron_energy = energies_out[index]

            # Adding the current event to the neutron event dictionary
            neutron_events["Event" + str(len(gamma_events) + 1)] = \
                [crash_xs[index], crash_ys[index], crash_zs[index], \
                source_xs[index], source_ys[index], source_zs[index], \
                energies_out[index], energies_in[index], particles_age[index], \
                particles_generation[index], targetAs[index], targetZs[index], \
                icode, fnpg_flags[index], ncases[index]
                ]

        else:
            assert 1==0, f"Non neutron/proton found in a (n,p)-scatter: {particles_out[index]}" + \
            f" found in NCASE {ncases[index]}"
    # If the ICODE is not 219, 225 or ICODE 100 with target A, Z = 1, 1, then the chain is reset
    else:
        gamma_chain = 0
        neutron_chain = 0

print(f"Gamma events: {len(gamma_events)}")
print(f"Neutron events: {len(neutron_events)}")
'''
# Finding out how frequent each interaction is

interactions={}

for index, i in enumerate(icodes):
    if i in interactions.keys() and fnpg_flags[index] == 1:
        interactions[i] += 1
    elif i not in interactions.keys() and fnpg_flags[index] == 1:
        interactions[i] = 1

for interaction, frequency in interactions.items():
    print(f"Interaction {interaction} happened {frequency} times")
'''

